version: "3"
services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    expose:
      - "5000"  # Chỉ expose port cho nginx, không map ra ngoài
    environment:
      - FLASK_ENV=production

  nginx:
    image: nginx:latest
    ports:
      - "80:80"  # Map port 80 ra ngoài
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf  # Mount file cấu hình nginx
    depends_on:
      - app