version: "3"
services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    volumes:
      - ./app:/app  # Mount thư mục app từ host vào container
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
    command: python app.py  # Chạy app trong dev mode

  tests:
    build:
      context: ./app
      dockerfile: Dockerfile
    volumes:
      - ./app:/app  # Mount thư mục app để theo dõi thay đổi
    entrypoint: ["pytest", "tests/test_app.py"]  # Chạy unit tests
    depends_on:
      - app